### ISSUE TITLE
Write output to file rather than to stderr

### ISSUE THREAD

**Issue by c3-tiffanyhui** [Shiranuit/node-segfault-handler#22]
Hello,

I would like to use this package to debug a segmentation fault (SIGSEGV) we are getting in a custom VS Code extension. Unfortunately I cannot get access to the stderr output and when the segmentation fault occurs the entire process dies. 
I am hoping that instead we can provide a file name to `registerHandler` and have the output written to the file, similar to https://github.com/ddopson/node-segfault-handler's feature. 

Thank you!

**Comment by Shiranuit** [comment]
Hi, thanks for the suggestion.
The PR that adds what you request has now been merged and the feature is now available starting with version `1.3.0`

Have a nice day.
